### ISSUE TITLE
Website essential features blocked

### ISSUE THREAD

**Issue by MK1338** [abp-filters/abp-filters-anti-cv#521]
**Website :**

* Link 1 (NSFW ads) : ``https://voiranime.com/anime/golden-kamuy-3/golden-kamuy-3-02-vostfr/``
* Link 2 (NSFW ads) : ``https://voiranime.com/anime/golden-kamuy-3/``

**Problems :** 

For Link 1 :
- When using search bar, no results are displayed
wordpress plugin used for search is "Ajax search lite pro"
- Google recaptcha challenge is blocked and can't confirm captcha solve
- Dropdown selector : Changing episode/changing player not working
For link 2 : 
"Premier EP" / "Dernier EP" buttons unclickable

### Screenshot(s) 

Captcha : https://i.gyazo.com/3fe6e8f3bf40998e1b07a6cca2f764e5.png
Search : https://i.gyazo.com/eeaf752711936470f54c5adcb0dd2e81.png
Dropdown selector : https://i.gyazo.com/443a3b2118e2641acdddb92b9328a064.png

### List all of your filter lists 

ABP filters
Liste FR+EasyList
Allow nonintrusive advertising

Configuration :

- Windows 10
- Google Chrome Version 87.0.4280.88 (Build officiel) (64 bits)
- Adblock Plus version: 3.10.1

### Other details 

Problem is happening with ublockOrigin and Adblock and Adblockplus

**Comment by mapx-** [comment]
fixed for uBO, very wrong filters in french list

**Comment by MK1338** [comment]
> fixed for uBO, very wrong filters in french list

Thank you so much @mapx- !
It fixed on ublockOrigin

Hopefully someone can fix it on Adblock and Adblockplus too

**Comment by smed79** [comment]
@MK1338 It was not intentional.

Anyway, Issue fixed.

**Comment by arsykan** [comment]
Thanks! @MK1338   @mapx-   @smed79 , I'll close it then.

**Comment by MK1338** [comment]
@arsykan Issue is still not fixed on Adblock and Adblockplus

**Comment by smed79** [comment]
@MK1338 Manually update your filter lists and test again.

In future, for **Liste FR** related issues, report directly at [lanik.us/viewforum.php?f=91](https://forums.lanik.us/viewforum.php?f=91) or [easylist/listefr/issues](https://github.com/easylist/listefr/issues)

**Comment by MK1338** [comment]
> @MK1338 Manually update your filter lists and test again.
> 
> In future, for **Liste FR** related issues, report directly at [lanik.us/viewforum.php?f=91](https://forums.lanik.us/viewforum.php?f=91) or [easylist/listefr/issues](https://github.com/easylist/listefr/issues)

I already did on Adblockplus
And issue is still there

**Comment by smed79** [comment]
submit an ABP [issue repport](https://help.eyeo.com/en/adblockplus/report-an-issue) and past the link here.

**Comment by mapx-** [comment]
@MK1338 update again, now is working

**Comment by MK1338** [comment]
@mapx- 
@smed79 

Yes ! now, it is working ! 

Thank you all for your time and support <3

**Comment by smed79** [comment]
you're welcome.

**Comment by MK1338** [comment]
@mapx- 

"Avast Secure Browser" adblocker is powered by Ublock
But seems it still has the same issue

is it something i need to contact avast directly about ?

**Comment by mapx-** [comment]
> powered by Ublock

If you check this page:
https://www.avast.com/c-best-ad-blockers

You'll see is about the fake ublock (with `ublock.org` page - blocked by the real uBO)

However, the issue was fixed by french list so whatever adblocker will get the updates in few days.

**Comment by smed79** [comment]
@MK1338 uBlock is acquired by AdBlock. If the problem persists, submit a ticket [here](https://tinyurl.com/ydyelbza).

**Comment by MK1338** [comment]
Hi,
The same problem started happening again today for users using **AdblockPlus** and **Adblock**

PS: I'm not facing any problems yet with ublock origin

**Comment by MK1338** [comment]
Hi,

The original issue started happening again with "ublock origin" after updating filters
